### ISSUE TITLE
I am trying to reach you

### ISSUE THREAD

**Issue by joker876** [MichaelPriebe/mystore#1]
Hello.
Before I even start, I want to tell you that I this issue is not related to mystore, but to an issue opened for wikitools ([link](https://github.com/MichaelPriebe/mystore/issues)). I am sorry for writing this here, feel free to delete this without even replying. 
I am writing this in the wrong repository only because I want to reach you really badly, and this seems to be the only one you are active in.
If you haven't already deleted this, please read the issue linked above. I would greatly appreciate your effort.

Thanks in advance,
joker876,
Admin and Bureaucrat of Hypixel Skyblock Wiki

**Comment by MichaelPriebe** [comment]
Responded on the wikitools issue.
